/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for BRANDREEDEMSCHEMA
 */
public class BRANDREEDEMSCHEMATest {
    private final BRANDREEDEMSCHEMA model = new BRANDREEDEMSCHEMA();

    /**
     * Model tests for BRANDREEDEMSCHEMA
     */
    @Test
    public void testBRANDREEDEMSCHEMA() {
        // TODO: test BRANDREEDEMSCHEMA
    }

    /**
     * Test the property 'brandID'
     */
    @Test
    public void brandIDTest() {
        // TODO: test brandID
    }

    /**
     * Test the property 'brandName'
     */
    @Test
    public void brandNameTest() {
        // TODO: test brandName
    }

    /**
     * Test the property 'brandLogo'
     */
    @Test
    public void brandLogoTest() {
        // TODO: test brandLogo
    }

    /**
     * Test the property 'brandNameSlug'
     */
    @Test
    public void brandNameSlugTest() {
        // TODO: test brandNameSlug
    }

    /**
     * Test the property 'brandPhone'
     */
    @Test
    public void brandPhoneTest() {
        // TODO: test brandPhone
    }

    /**
     * Test the property 'brandAddress'
     */
    @Test
    public void brandAddressTest() {
        // TODO: test brandAddress
    }

    /**
     * Test the property 'brandDesc'
     */
    @Test
    public void brandDescTest() {
        // TODO: test brandDesc
    }

    /**
     * Test the property 'brandServiceGuide'
     */
    @Test
    public void brandServiceGuideTest() {
        // TODO: test brandServiceGuide
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'categoryNm'
     */
    @Test
    public void categoryNmTest() {
        // TODO: test categoryNm
    }

    /**
     * Test the property 'categoryImg'
     */
    @Test
    public void categoryImgTest() {
        // TODO: test categoryImg
    }

}
