/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.STORESSCHEMA;
import com.gotit.sdk.model.USAGEMETHODSCHEMA;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for BRANDDETAIL
 */
public class BRANDDETAILTest {
    private final BRANDDETAIL model = new BRANDDETAIL();

    /**
     * Model tests for BRANDDETAIL
     */
    @Test
    public void testBRANDDETAIL() {
        // TODO: test BRANDDETAIL
    }

    /**
     * Test the property 'brandId'
     */
    @Test
    public void brandIdTest() {
        // TODO: test brandId
    }

    /**
     * Test the property 'brandNm'
     */
    @Test
    public void brandNmTest() {
        // TODO: test brandNm
    }

    /**
     * Test the property 'brandAddr'
     */
    @Test
    public void brandAddrTest() {
        // TODO: test brandAddr
    }

    /**
     * Test the property 'brandLogo'
     */
    @Test
    public void brandLogoTest() {
        // TODO: test brandLogo
    }

    /**
     * Test the property 'serviceGuide'
     */
    @Test
    public void serviceGuideTest() {
        // TODO: test serviceGuide
    }

    /**
     * Test the property 'stores'
     */
    @Test
    public void storesTest() {
        // TODO: test stores
    }

    /**
     * Test the property 'usageMethods'
     */
    @Test
    public void usageMethodsTest() {
        // TODO: test usageMethods
    }

}
