/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CATEGORIESDETAIL
 */
public class CATEGORIESDETAILTest {
    private final CATEGORIESDETAIL model = new CATEGORIESDETAIL();

    /**
     * Model tests for CATEGORIESDETAIL
     */
    @Test
    public void testCATEGORIESDETAIL() {
        // TODO: test CATEGORIESDETAIL
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'categoryNm'
     */
    @Test
    public void categoryNmTest() {
        // TODO: test categoryNm
    }

    /**
     * Test the property 'categoryImg'
     */
    @Test
    public void categoryImgTest() {
        // TODO: test categoryImg
    }

    /**
     * Test the property 'slug'
     */
    @Test
    public void slugTest() {
        // TODO: test slug
    }

    /**
     * Test the property 'order'
     */
    @Test
    public void orderTest() {
        // TODO: test order
    }

}
