/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.PAGINGSCHEMA;
import com.gotit.sdk.model.PRODUCTSALLDETAIL;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PRODUCTSRESPONSEDataInner
 */
public class PRODUCTSRESPONSEDataInnerTest {
    private final PRODUCTSRESPONSEDataInner model = new PRODUCTSRESPONSEDataInner();

    /**
     * Model tests for PRODUCTSRESPONSEDataInner
     */
    @Test
    public void testPRODUCTSRESPONSEDataInner() {
        // TODO: test PRODUCTSRESPONSEDataInner
    }

    /**
     * Test the property 'productList'
     */
    @Test
    public void productListTest() {
        // TODO: test productList
    }

    /**
     * Test the property 'pagination'
     */
    @Test
    public void paginationTest() {
        // TODO: test pagination
    }

}
