/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PRODUCTPRICESCHEMA
 */
public class PRODUCTPRICESCHEMATest {
    private final PRODUCTPRICESCHEMA model = new PRODUCTPRICESCHEMA();

    /**
     * Model tests for PRODUCTPRICESCHEMA
     */
    @Test
    public void testPRODUCTPRICESCHEMA() {
        // TODO: test PRODUCTPRICESCHEMA
    }

    /**
     * Test the property 'priceId'
     */
    @Test
    public void priceIdTest() {
        // TODO: test priceId
    }

    /**
     * Test the property 'priceNm'
     */
    @Test
    public void priceNmTest() {
        // TODO: test priceNm
    }

    /**
     * Test the property 'priceValue'
     */
    @Test
    public void priceValueTest() {
        // TODO: test priceValue
    }

}
