/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.PAGINGSCHEMA;
import com.gotit.sdk.model.PRODUCTPRICESCHEMA;
import com.gotit.sdk.model.STOREPRODUCTSCHEMA;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for PRODUCTSALLDETAIL
 */
public class PRODUCTSALLDETAILTest {
    private final PRODUCTSALLDETAIL model = new PRODUCTSALLDETAIL();

    /**
     * Model tests for PRODUCTSALLDETAIL
     */
    @Test
    public void testPRODUCTSALLDETAIL() {
        // TODO: test PRODUCTSALLDETAIL
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productNm'
     */
    @Test
    public void productNmTest() {
        // TODO: test productNm
    }

    /**
     * Test the property 'productImg'
     */
    @Test
    public void productImgTest() {
        // TODO: test productImg
    }

    /**
     * Test the property 'productDesc'
     */
    @Test
    public void productDescTest() {
        // TODO: test productDesc
    }

    /**
     * Test the property 'productShortDesc'
     */
    @Test
    public void productShortDescTest() {
        // TODO: test productShortDesc
    }

    /**
     * Test the property 'terms'
     */
    @Test
    public void termsTest() {
        // TODO: test terms
    }

    /**
     * Test the property 'brandId'
     */
    @Test
    public void brandIdTest() {
        // TODO: test brandId
    }

    /**
     * Test the property 'brandNm'
     */
    @Test
    public void brandNmTest() {
        // TODO: test brandNm
    }

    /**
     * Test the property 'brandLogo'
     */
    @Test
    public void brandLogoTest() {
        // TODO: test brandLogo
    }

    /**
     * Test the property 'brandServiceGuide'
     */
    @Test
    public void brandServiceGuideTest() {
        // TODO: test brandServiceGuide
    }

    /**
     * Test the property 'categoryId'
     */
    @Test
    public void categoryIdTest() {
        // TODO: test categoryId
    }

    /**
     * Test the property 'categoryNm'
     */
    @Test
    public void categoryNmTest() {
        // TODO: test categoryNm
    }

    /**
     * Test the property 'categoryImg'
     */
    @Test
    public void categoryImgTest() {
        // TODO: test categoryImg
    }

    /**
     * Test the property 'productType'
     */
    @Test
    public void productTypeTest() {
        // TODO: test productType
    }

    /**
     * Test the property 'prices'
     */
    @Test
    public void pricesTest() {
        // TODO: test prices
    }

    /**
     * Test the property 'link'
     */
    @Test
    public void linkTest() {
        // TODO: test link
    }

    /**
     * Test the property 'storeList'
     */
    @Test
    public void storeListTest() {
        // TODO: test storeList
    }

    /**
     * Test the property 'totalStore'
     */
    @Test
    public void totalStoreTest() {
        // TODO: test totalStore
    }

    /**
     * Test the property 'storePagination'
     */
    @Test
    public void storePaginationTest() {
        // TODO: test storePagination
    }

}
