/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for REQUESTSENDVOUCHERBYZNS
 */
public class REQUESTSENDVOUCHERBYZNSTest {
    private final REQUESTSENDVOUCHERBYZNS model = new REQUESTSENDVOUCHERBYZNS();

    /**
     * Model tests for REQUESTSENDVOUCHERBYZNS
     */
    @Test
    public void testREQUESTSENDVOUCHERBYZNS() {
        // TODO: test REQUESTSENDVOUCHERBYZNS
    }

    /**
     * Test the property 'phoneNo'
     */
    @Test
    public void phoneNoTest() {
        // TODO: test phoneNo
    }

    /**
     * Test the property 'receiverNm'
     */
    @Test
    public void receiverNmTest() {
        // TODO: test receiverNm
    }

    /**
     * Test the property 'voucherSerials'
     */
    @Test
    public void voucherSerialsTest() {
        // TODO: test voucherSerials
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

}
