/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for REQUESTCREATEVOUCHERLINKV
 */
public class REQUESTCREATEVOUCHERLINKVTest {
    private final REQUESTCREATEVOUCHERLINKV model = new REQUESTCREATEVOUCHERLINKV();

    /**
     * Model tests for REQUESTCREATEVOUCHERLINKV
     */
    @Test
    public void testREQUESTCREATEVOUCHERLINKV() {
        // TODO: test REQUESTCREATEVOUCHERLINKV
    }

    /**
     * Test the property 'productId'
     */
    @Test
    public void productIdTest() {
        // TODO: test productId
    }

    /**
     * Test the property 'productPriceId'
     */
    @Test
    public void productPriceIdTest() {
        // TODO: test productPriceId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    public void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'orderName'
     */
    @Test
    public void orderNameTest() {
        // TODO: test orderName
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'transactionRefId'
     */
    @Test
    public void transactionRefIdTest() {
        // TODO: test transactionRefId
    }

    /**
     * Test the property 'useOtp'
     */
    @Test
    public void useOtpTest() {
        // TODO: test useOtp
    }

    /**
     * Test the property 'otpType'
     */
    @Test
    public void otpTypeTest() {
        // TODO: test otpType
    }

    /**
     * Test the property 'password'
     */
    @Test
    public void passwordTest() {
        // TODO: test password
    }

    /**
     * Test the property 'receiverName'
     */
    @Test
    public void receiverNameTest() {
        // TODO: test receiverName
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'email'
     */
    @Test
    public void emailTest() {
        // TODO: test email
    }

    /**
     * Test the property 'signature'
     */
    @Test
    public void signatureTest() {
        // TODO: test signature
    }

    /**
     * Test the property 'activeDate'
     */
    @Test
    public void activeDateTest() {
        // TODO: test activeDate
    }

    /**
     * Test the property 'isConvertToCoverLink'
     */
    @Test
    public void isConvertToCoverLinkTest() {
        // TODO: test isConvertToCoverLink
    }

}
