/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for STOREPRODUCTSCHEMA
 */
public class STOREPRODUCTSCHEMATest {
    private final STOREPRODUCTSCHEMA model = new STOREPRODUCTSCHEMA();

    /**
     * Model tests for STOREPRODUCTSCHEMA
     */
    @Test
    public void testSTOREPRODUCTSCHEMA() {
        // TODO: test STOREPRODUCTSCHEMA
    }

    /**
     * Test the property 'storeId'
     */
    @Test
    public void storeIdTest() {
        // TODO: test storeId
    }

    /**
     * Test the property 'storeNm'
     */
    @Test
    public void storeNmTest() {
        // TODO: test storeNm
    }

    /**
     * Test the property 'storeAddr'
     */
    @Test
    public void storeAddrTest() {
        // TODO: test storeAddr
    }

    /**
     * Test the property 'lat'
     */
    @Test
    public void latTest() {
        // TODO: test lat
    }

    /**
     * Test the property '_long'
     */
    @Test
    public void _longTest() {
        // TODO: test _long
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'cityId'
     */
    @Test
    public void cityIdTest() {
        // TODO: test cityId
    }

    /**
     * Test the property 'city'
     */
    @Test
    public void cityTest() {
        // TODO: test city
    }

    /**
     * Test the property 'distId'
     */
    @Test
    public void distIdTest() {
        // TODO: test distId
    }

    /**
     * Test the property 'district'
     */
    @Test
    public void districtTest() {
        // TODO: test district
    }

}
