/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOUCHERCHECKZNSRESPONSEData
 */
public class VOUCHERCHECKZNSRESPONSEDataTest {
    private final VOUCHERCHECKZNSRESPONSEData model = new VOUCHERCHECKZNSRESPONSEData();

    /**
     * Model tests for VOUCHERCHECKZNSRESPONSEData
     */
    @Test
    public void testVOUCHERCHECKZNSRESPONSEData() {
        // TODO: test VOUCHERCHECKZNSRESPONSEData
    }

    /**
     * Test the property 'serials'
     */
    @Test
    public void serialsTest() {
        // TODO: test serials
    }

}
