/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.VOUCHERVSCHEMAProduct;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOUCHERVSCHEMA
 */
public class VOUCHERVSCHEMATest {
    private final VOUCHERVSCHEMA model = new VOUCHERVSCHEMA();

    /**
     * Model tests for VOUCHERVSCHEMA
     */
    @Test
    public void testVOUCHERVSCHEMA() {
        // TODO: test VOUCHERVSCHEMA
    }

    /**
     * Test the property 'transactionRefId'
     */
    @Test
    public void transactionRefIdTest() {
        // TODO: test transactionRefId
    }

    /**
     * Test the property 'voucherCode'
     */
    @Test
    public void voucherCodeTest() {
        // TODO: test voucherCode
    }

    /**
     * Test the property 'voucherLink'
     */
    @Test
    public void voucherLinkTest() {
        // TODO: test voucherLink
    }

    /**
     * Test the property 'voucherLinkCode'
     */
    @Test
    public void voucherLinkCodeTest() {
        // TODO: test voucherLinkCode
    }

    /**
     * Test the property 'voucherImageLink'
     */
    @Test
    public void voucherImageLinkTest() {
        // TODO: test voucherImageLink
    }

    /**
     * Test the property 'voucherCoverLink'
     */
    @Test
    public void voucherCoverLinkTest() {
        // TODO: test voucherCoverLink
    }

    /**
     * Test the property 'voucherCoverLinkCode'
     */
    @Test
    public void voucherCoverLinkCodeTest() {
        // TODO: test voucherCoverLinkCode
    }

    /**
     * Test the property 'voucherSerial'
     */
    @Test
    public void voucherSerialTest() {
        // TODO: test voucherSerial
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

}
