/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOUCHERSENDZNSRESPONSEData
 */
public class VOUCHERSENDZNSRESPONSEDataTest {
    private final VOUCHERSENDZNSRESPONSEData model = new VOUCHERSENDZNSRESPONSEData();

    /**
     * Model tests for VOUCHERSENDZNSRESPONSEData
     */
    @Test
    public void testVOUCHERSENDZNSRESPONSEData() {
        // TODO: test VOUCHERSENDZNSRESPONSEData
    }

    /**
     * Test the property 'transactionId'
     */
    @Test
    public void transactionIdTest() {
        // TODO: test transactionId
    }

}
