/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.PRODUCTV;
import com.gotit.sdk.model.STORESSCHEMA;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOUCHERCHECKSCHEMADETAIL
 */
public class VOUCHERCHECKSCHEMADETAILTest {
    private final VOUCHERCHECKSCHEMADETAIL model = new VOUCHERCHECKSCHEMADETAIL();

    /**
     * Model tests for VOUCHERCHECKSCHEMADETAIL
     */
    @Test
    public void testVOUCHERCHECKSCHEMADETAIL() {
        // TODO: test VOUCHERCHECKSCHEMADETAIL
    }

    /**
     * Test the property 'transactionRefId'
     */
    @Test
    public void transactionRefIdTest() {
        // TODO: test transactionRefId
    }

    /**
     * Test the property 'voucherCode'
     */
    @Test
    public void voucherCodeTest() {
        // TODO: test voucherCode
    }

    /**
     * Test the property 'voucherLink'
     */
    @Test
    public void voucherLinkTest() {
        // TODO: test voucherLink
    }

    /**
     * Test the property 'voucherCoverLink'
     */
    @Test
    public void voucherCoverLinkTest() {
        // TODO: test voucherCoverLink
    }

    /**
     * Test the property 'voucherSerial'
     */
    @Test
    public void voucherSerialTest() {
        // TODO: test voucherSerial
    }

    /**
     * Test the property 'groupLink'
     */
    @Test
    public void groupLinkTest() {
        // TODO: test groupLink
    }

    /**
     * Test the property 'groupVoucherSerial'
     */
    @Test
    public void groupVoucherSerialTest() {
        // TODO: test groupVoucherSerial
    }

    /**
     * Test the property 'groupCoverLink'
     */
    @Test
    public void groupCoverLinkTest() {
        // TODO: test groupCoverLink
    }

    /**
     * Test the property 'voucherLinkCode'
     */
    @Test
    public void voucherLinkCodeTest() {
        // TODO: test voucherLinkCode
    }

    /**
     * Test the property 'voucherImageLink'
     */
    @Test
    public void voucherImageLinkTest() {
        // TODO: test voucherImageLink
    }

    /**
     * Test the property 'expiryDate'
     */
    @Test
    public void expiryDateTest() {
        // TODO: test expiryDate
    }

    /**
     * Test the property 'stateCode'
     */
    @Test
    public void stateCodeTest() {
        // TODO: test stateCode
    }

    /**
     * Test the property 'stateText'
     */
    @Test
    public void stateTextTest() {
        // TODO: test stateText
    }

    /**
     * Test the property 'usedStore'
     */
    @Test
    public void usedStoreTest() {
        // TODO: test usedStore
    }

    /**
     * Test the property 'usedTime'
     */
    @Test
    public void usedTimeTest() {
        // TODO: test usedTime
    }

    /**
     * Test the property 'usedBrand'
     */
    @Test
    public void usedBrandTest() {
        // TODO: test usedBrand
    }

    /**
     * Test the property 'product'
     */
    @Test
    public void productTest() {
        // TODO: test product
    }

}
