/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.VOUCHERCHECKSCHEMADETAIL;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for VOUCHERCHECKSCHEMA
 */
public class VOUCHERCHECKSCHEMATest {
    private final VOUCHERCHECKSCHEMA model = new VOUCHERCHECKSCHEMA();

    /**
     * Model tests for VOUCHERCHECKSCHEMA
     */
    @Test
    public void testVOUCHERCHECKSCHEMA() {
        // TODO: test VOUCHERCHECKSCHEMA
    }

    /**
     * Test the property 'transactionRefId'
     */
    @Test
    public void transactionRefIdTest() {
        // TODO: test transactionRefId
    }

    /**
     * Test the property 'vouchers'
     */
    @Test
    public void vouchersTest() {
        // TODO: test vouchers
    }

}
