/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gotit.sdk.JSON;

/**
 * BRANDREEDEMSCHEMA
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T09:04:05.866297444Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class BRANDREEDEMSCHEMA {
  public static final String SERIALIZED_NAME_BRAND_I_D = "brandID";
  @SerializedName(SERIALIZED_NAME_BRAND_I_D)
  @javax.annotation.Nullable
  private Integer brandID;

  public static final String SERIALIZED_NAME_BRAND_NAME = "brandName";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME)
  @javax.annotation.Nullable
  private String brandName;

  public static final String SERIALIZED_NAME_BRAND_LOGO = "brandLogo";
  @SerializedName(SERIALIZED_NAME_BRAND_LOGO)
  @javax.annotation.Nullable
  private String brandLogo;

  public static final String SERIALIZED_NAME_BRAND_NAME_SLUG = "brandNameSlug";
  @SerializedName(SERIALIZED_NAME_BRAND_NAME_SLUG)
  @javax.annotation.Nullable
  private String brandNameSlug;

  public static final String SERIALIZED_NAME_BRAND_PHONE = "brandPhone";
  @SerializedName(SERIALIZED_NAME_BRAND_PHONE)
  @javax.annotation.Nullable
  private String brandPhone;

  public static final String SERIALIZED_NAME_BRAND_ADDRESS = "brandAddress";
  @SerializedName(SERIALIZED_NAME_BRAND_ADDRESS)
  @javax.annotation.Nullable
  private String brandAddress;

  public static final String SERIALIZED_NAME_BRAND_DESC = "brandDesc";
  @SerializedName(SERIALIZED_NAME_BRAND_DESC)
  @javax.annotation.Nullable
  private String brandDesc;

  public static final String SERIALIZED_NAME_BRAND_SERVICE_GUIDE = "brandServiceGuide";
  @SerializedName(SERIALIZED_NAME_BRAND_SERVICE_GUIDE)
  @javax.annotation.Nullable
  private String brandServiceGuide;

  public static final String SERIALIZED_NAME_CATEGORY_ID = "categoryId";
  @SerializedName(SERIALIZED_NAME_CATEGORY_ID)
  @javax.annotation.Nullable
  private Integer categoryId;

  public static final String SERIALIZED_NAME_CATEGORY_NM = "categoryNm";
  @SerializedName(SERIALIZED_NAME_CATEGORY_NM)
  @javax.annotation.Nullable
  private String categoryNm;

  public static final String SERIALIZED_NAME_CATEGORY_IMG = "categoryImg";
  @SerializedName(SERIALIZED_NAME_CATEGORY_IMG)
  @javax.annotation.Nullable
  private String categoryImg;

  public BRANDREEDEMSCHEMA() {
  }

  public BRANDREEDEMSCHEMA brandID(@javax.annotation.Nullable Integer brandID) {
    this.brandID = brandID;
    return this;
  }

  /**
   * Brand id
   * @return brandID
   */
  @javax.annotation.Nullable
  public Integer getBrandID() {
    return brandID;
  }

  public void setBrandID(@javax.annotation.Nullable Integer brandID) {
    this.brandID = brandID;
  }


  public BRANDREEDEMSCHEMA brandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
    return this;
  }

  /**
   * Brand name
   * @return brandName
   */
  @javax.annotation.Nullable
  public String getBrandName() {
    return brandName;
  }

  public void setBrandName(@javax.annotation.Nullable String brandName) {
    this.brandName = brandName;
  }


  public BRANDREEDEMSCHEMA brandLogo(@javax.annotation.Nullable String brandLogo) {
    this.brandLogo = brandLogo;
    return this;
  }

  /**
   * Link to brand logo image
   * @return brandLogo
   */
  @javax.annotation.Nullable
  public String getBrandLogo() {
    return brandLogo;
  }

  public void setBrandLogo(@javax.annotation.Nullable String brandLogo) {
    this.brandLogo = brandLogo;
  }


  public BRANDREEDEMSCHEMA brandNameSlug(@javax.annotation.Nullable String brandNameSlug) {
    this.brandNameSlug = brandNameSlug;
    return this;
  }

  /**
   * Brand name slug
   * @return brandNameSlug
   */
  @javax.annotation.Nullable
  public String getBrandNameSlug() {
    return brandNameSlug;
  }

  public void setBrandNameSlug(@javax.annotation.Nullable String brandNameSlug) {
    this.brandNameSlug = brandNameSlug;
  }


  public BRANDREEDEMSCHEMA brandPhone(@javax.annotation.Nullable String brandPhone) {
    this.brandPhone = brandPhone;
    return this;
  }

  /**
   * Brand Phone Number
   * @return brandPhone
   */
  @javax.annotation.Nullable
  public String getBrandPhone() {
    return brandPhone;
  }

  public void setBrandPhone(@javax.annotation.Nullable String brandPhone) {
    this.brandPhone = brandPhone;
  }


  public BRANDREEDEMSCHEMA brandAddress(@javax.annotation.Nullable String brandAddress) {
    this.brandAddress = brandAddress;
    return this;
  }

  /**
   * Address of brand
   * @return brandAddress
   */
  @javax.annotation.Nullable
  public String getBrandAddress() {
    return brandAddress;
  }

  public void setBrandAddress(@javax.annotation.Nullable String brandAddress) {
    this.brandAddress = brandAddress;
  }


  public BRANDREEDEMSCHEMA brandDesc(@javax.annotation.Nullable String brandDesc) {
    this.brandDesc = brandDesc;
    return this;
  }

  /**
   * Brand Description
   * @return brandDesc
   */
  @javax.annotation.Nullable
  public String getBrandDesc() {
    return brandDesc;
  }

  public void setBrandDesc(@javax.annotation.Nullable String brandDesc) {
    this.brandDesc = brandDesc;
  }


  public BRANDREEDEMSCHEMA brandServiceGuide(@javax.annotation.Nullable String brandServiceGuide) {
    this.brandServiceGuide = brandServiceGuide;
    return this;
  }

  /**
   * Describe the brand&#39;s terms of reference (T&amp;C). HTML format
   * @return brandServiceGuide
   */
  @javax.annotation.Nullable
  public String getBrandServiceGuide() {
    return brandServiceGuide;
  }

  public void setBrandServiceGuide(@javax.annotation.Nullable String brandServiceGuide) {
    this.brandServiceGuide = brandServiceGuide;
  }


  public BRANDREEDEMSCHEMA categoryId(@javax.annotation.Nullable Integer categoryId) {
    this.categoryId = categoryId;
    return this;
  }

  /**
   * Category Id
   * @return categoryId
   */
  @javax.annotation.Nullable
  public Integer getCategoryId() {
    return categoryId;
  }

  public void setCategoryId(@javax.annotation.Nullable Integer categoryId) {
    this.categoryId = categoryId;
  }


  public BRANDREEDEMSCHEMA categoryNm(@javax.annotation.Nullable String categoryNm) {
    this.categoryNm = categoryNm;
    return this;
  }

  /**
   * Category Name
   * @return categoryNm
   */
  @javax.annotation.Nullable
  public String getCategoryNm() {
    return categoryNm;
  }

  public void setCategoryNm(@javax.annotation.Nullable String categoryNm) {
    this.categoryNm = categoryNm;
  }


  public BRANDREEDEMSCHEMA categoryImg(@javax.annotation.Nullable String categoryImg) {
    this.categoryImg = categoryImg;
    return this;
  }

  /**
   * Category Image Logo
   * @return categoryImg
   */
  @javax.annotation.Nullable
  public String getCategoryImg() {
    return categoryImg;
  }

  public void setCategoryImg(@javax.annotation.Nullable String categoryImg) {
    this.categoryImg = categoryImg;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BRANDREEDEMSCHEMA BRAND_REEDEM_SCHEMA = (BRANDREEDEMSCHEMA) o;
    return Objects.equals(this.brandID, BRAND_REEDEM_SCHEMA.brandID) &&
        Objects.equals(this.brandName, BRAND_REEDEM_SCHEMA.brandName) &&
        Objects.equals(this.brandLogo, BRAND_REEDEM_SCHEMA.brandLogo) &&
        Objects.equals(this.brandNameSlug, BRAND_REEDEM_SCHEMA.brandNameSlug) &&
        Objects.equals(this.brandPhone, BRAND_REEDEM_SCHEMA.brandPhone) &&
        Objects.equals(this.brandAddress, BRAND_REEDEM_SCHEMA.brandAddress) &&
        Objects.equals(this.brandDesc, BRAND_REEDEM_SCHEMA.brandDesc) &&
        Objects.equals(this.brandServiceGuide, BRAND_REEDEM_SCHEMA.brandServiceGuide) &&
        Objects.equals(this.categoryId, BRAND_REEDEM_SCHEMA.categoryId) &&
        Objects.equals(this.categoryNm, BRAND_REEDEM_SCHEMA.categoryNm) &&
        Objects.equals(this.categoryImg, BRAND_REEDEM_SCHEMA.categoryImg);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(brandID, brandName, brandLogo, brandNameSlug, brandPhone, brandAddress, brandDesc, brandServiceGuide, categoryId, categoryNm, categoryImg);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BRANDREEDEMSCHEMA {\n");
    sb.append("    brandID: ").append(toIndentedString(brandID)).append("\n");
    sb.append("    brandName: ").append(toIndentedString(brandName)).append("\n");
    sb.append("    brandLogo: ").append(toIndentedString(brandLogo)).append("\n");
    sb.append("    brandNameSlug: ").append(toIndentedString(brandNameSlug)).append("\n");
    sb.append("    brandPhone: ").append(toIndentedString(brandPhone)).append("\n");
    sb.append("    brandAddress: ").append(toIndentedString(brandAddress)).append("\n");
    sb.append("    brandDesc: ").append(toIndentedString(brandDesc)).append("\n");
    sb.append("    brandServiceGuide: ").append(toIndentedString(brandServiceGuide)).append("\n");
    sb.append("    categoryId: ").append(toIndentedString(categoryId)).append("\n");
    sb.append("    categoryNm: ").append(toIndentedString(categoryNm)).append("\n");
    sb.append("    categoryImg: ").append(toIndentedString(categoryImg)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("brandID");
    openapiFields.add("brandName");
    openapiFields.add("brandLogo");
    openapiFields.add("brandNameSlug");
    openapiFields.add("brandPhone");
    openapiFields.add("brandAddress");
    openapiFields.add("brandDesc");
    openapiFields.add("brandServiceGuide");
    openapiFields.add("categoryId");
    openapiFields.add("categoryNm");
    openapiFields.add("categoryImg");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to BRANDREEDEMSCHEMA
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!BRANDREEDEMSCHEMA.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in BRANDREEDEMSCHEMA is not found in the empty JSON string", BRANDREEDEMSCHEMA.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!BRANDREEDEMSCHEMA.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `BRANDREEDEMSCHEMA` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("brandName") != null && !jsonObj.get("brandName").isJsonNull()) && !jsonObj.get("brandName").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandName` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandName").toString()));
      }
      if ((jsonObj.get("brandLogo") != null && !jsonObj.get("brandLogo").isJsonNull()) && !jsonObj.get("brandLogo").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandLogo` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandLogo").toString()));
      }
      if ((jsonObj.get("brandNameSlug") != null && !jsonObj.get("brandNameSlug").isJsonNull()) && !jsonObj.get("brandNameSlug").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandNameSlug` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandNameSlug").toString()));
      }
      if ((jsonObj.get("brandPhone") != null && !jsonObj.get("brandPhone").isJsonNull()) && !jsonObj.get("brandPhone").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandPhone` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandPhone").toString()));
      }
      if ((jsonObj.get("brandAddress") != null && !jsonObj.get("brandAddress").isJsonNull()) && !jsonObj.get("brandAddress").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandAddress` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandAddress").toString()));
      }
      if ((jsonObj.get("brandDesc") != null && !jsonObj.get("brandDesc").isJsonNull()) && !jsonObj.get("brandDesc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandDesc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandDesc").toString()));
      }
      if ((jsonObj.get("brandServiceGuide") != null && !jsonObj.get("brandServiceGuide").isJsonNull()) && !jsonObj.get("brandServiceGuide").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandServiceGuide` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandServiceGuide").toString()));
      }
      if ((jsonObj.get("categoryNm") != null && !jsonObj.get("categoryNm").isJsonNull()) && !jsonObj.get("categoryNm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `categoryNm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("categoryNm").toString()));
      }
      if ((jsonObj.get("categoryImg") != null && !jsonObj.get("categoryImg").isJsonNull()) && !jsonObj.get("categoryImg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `categoryImg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("categoryImg").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!BRANDREEDEMSCHEMA.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'BRANDREEDEMSCHEMA' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<BRANDREEDEMSCHEMA> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(BRANDREEDEMSCHEMA.class));

       return (TypeAdapter<T>) new TypeAdapter<BRANDREEDEMSCHEMA>() {
           @Override
           public void write(JsonWriter out, BRANDREEDEMSCHEMA value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public BRANDREEDEMSCHEMA read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of BRANDREEDEMSCHEMA given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of BRANDREEDEMSCHEMA
   * @throws IOException if the JSON string is invalid with respect to BRANDREEDEMSCHEMA
   */
  public static BRANDREEDEMSCHEMA fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, BRANDREEDEMSCHEMA.class);
  }

  /**
   * Convert an instance of BRANDREEDEMSCHEMA to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

