/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gotit.sdk.JSON;

/**
 * GROUPVOUCHERSCHEMA
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T09:04:05.866297444Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class GROUPVOUCHERSCHEMA {
  public static final String SERIALIZED_NAME_VOUCHER_LINK = "voucherLink";
  @SerializedName(SERIALIZED_NAME_VOUCHER_LINK)
  @javax.annotation.Nullable
  private String voucherLink;

  public static final String SERIALIZED_NAME_VOUCHER_LINK_CODE = "voucherLinkCode";
  @SerializedName(SERIALIZED_NAME_VOUCHER_LINK_CODE)
  @javax.annotation.Nullable
  private String voucherLinkCode;

  public static final String SERIALIZED_NAME_VOUCHER_SERIAL = "voucherSerial";
  @SerializedName(SERIALIZED_NAME_VOUCHER_SERIAL)
  @javax.annotation.Nullable
  private String voucherSerial;

  public GROUPVOUCHERSCHEMA() {
  }

  public GROUPVOUCHERSCHEMA voucherLink(@javax.annotation.Nullable String voucherLink) {
    this.voucherLink = voucherLink;
    return this;
  }

  /**
   * Link of voucher
   * @return voucherLink
   */
  @javax.annotation.Nullable
  public String getVoucherLink() {
    return voucherLink;
  }

  public void setVoucherLink(@javax.annotation.Nullable String voucherLink) {
    this.voucherLink = voucherLink;
  }


  public GROUPVOUCHERSCHEMA voucherLinkCode(@javax.annotation.Nullable String voucherLinkCode) {
    this.voucherLinkCode = voucherLinkCode;
    return this;
  }

  /**
   * Last 8 characters of voucher link
   * @return voucherLinkCode
   */
  @javax.annotation.Nullable
  public String getVoucherLinkCode() {
    return voucherLinkCode;
  }

  public void setVoucherLinkCode(@javax.annotation.Nullable String voucherLinkCode) {
    this.voucherLinkCode = voucherLinkCode;
  }


  public GROUPVOUCHERSCHEMA voucherSerial(@javax.annotation.Nullable String voucherSerial) {
    this.voucherSerial = voucherSerial;
    return this;
  }

  /**
   * Is a unique code to identify voucher link v and is not valid for use. For example: V1562342ET2
   * @return voucherSerial
   */
  @javax.annotation.Nullable
  public String getVoucherSerial() {
    return voucherSerial;
  }

  public void setVoucherSerial(@javax.annotation.Nullable String voucherSerial) {
    this.voucherSerial = voucherSerial;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GROUPVOUCHERSCHEMA GROUP_VOUCHER_SCHEMA = (GROUPVOUCHERSCHEMA) o;
    return Objects.equals(this.voucherLink, GROUP_VOUCHER_SCHEMA.voucherLink) &&
        Objects.equals(this.voucherLinkCode, GROUP_VOUCHER_SCHEMA.voucherLinkCode) &&
        Objects.equals(this.voucherSerial, GROUP_VOUCHER_SCHEMA.voucherSerial);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(voucherLink, voucherLinkCode, voucherSerial);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GROUPVOUCHERSCHEMA {\n");
    sb.append("    voucherLink: ").append(toIndentedString(voucherLink)).append("\n");
    sb.append("    voucherLinkCode: ").append(toIndentedString(voucherLinkCode)).append("\n");
    sb.append("    voucherSerial: ").append(toIndentedString(voucherSerial)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("voucherLink");
    openapiFields.add("voucherLinkCode");
    openapiFields.add("voucherSerial");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to GROUPVOUCHERSCHEMA
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!GROUPVOUCHERSCHEMA.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in GROUPVOUCHERSCHEMA is not found in the empty JSON string", GROUPVOUCHERSCHEMA.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!GROUPVOUCHERSCHEMA.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `GROUPVOUCHERSCHEMA` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("voucherLink") != null && !jsonObj.get("voucherLink").isJsonNull()) && !jsonObj.get("voucherLink").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucherLink` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucherLink").toString()));
      }
      if ((jsonObj.get("voucherLinkCode") != null && !jsonObj.get("voucherLinkCode").isJsonNull()) && !jsonObj.get("voucherLinkCode").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucherLinkCode` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucherLinkCode").toString()));
      }
      if ((jsonObj.get("voucherSerial") != null && !jsonObj.get("voucherSerial").isJsonNull()) && !jsonObj.get("voucherSerial").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucherSerial` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucherSerial").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!GROUPVOUCHERSCHEMA.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'GROUPVOUCHERSCHEMA' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<GROUPVOUCHERSCHEMA> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(GROUPVOUCHERSCHEMA.class));

       return (TypeAdapter<T>) new TypeAdapter<GROUPVOUCHERSCHEMA>() {
           @Override
           public void write(JsonWriter out, GROUPVOUCHERSCHEMA value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public GROUPVOUCHERSCHEMA read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of GROUPVOUCHERSCHEMA given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of GROUPVOUCHERSCHEMA
   * @throws IOException if the JSON string is invalid with respect to GROUPVOUCHERSCHEMA
   */
  public static GROUPVOUCHERSCHEMA fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, GROUPVOUCHERSCHEMA.class);
  }

  /**
   * Convert an instance of GROUPVOUCHERSCHEMA to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

