/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.PRODUCTPRICESCHEMA;
import com.gotit.sdk.model.STOREPAGINGSCHEMA;
import com.gotit.sdk.model.STOREPRODUCTSCHEMA;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gotit.sdk.JSON;

/**
 * PRODUCTSVOUCHERCHECK
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T09:04:05.866297444Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class PRODUCTSVOUCHERCHECK {
  public static final String SERIALIZED_NAME_PRODUCT_ID = "productId";
  @SerializedName(SERIALIZED_NAME_PRODUCT_ID)
  @javax.annotation.Nullable
  private Integer productId;

  public static final String SERIALIZED_NAME_PRODUCT_NM = "productNm";
  @SerializedName(SERIALIZED_NAME_PRODUCT_NM)
  @javax.annotation.Nullable
  private String productNm;

  public static final String SERIALIZED_NAME_PRODUCT_IMG = "productImg";
  @SerializedName(SERIALIZED_NAME_PRODUCT_IMG)
  @javax.annotation.Nullable
  private String productImg;

  public static final String SERIALIZED_NAME_BRAND_ID = "brandId";
  @SerializedName(SERIALIZED_NAME_BRAND_ID)
  @javax.annotation.Nullable
  private Integer brandId;

  public static final String SERIALIZED_NAME_BRAND_NM = "brandNm";
  @SerializedName(SERIALIZED_NAME_BRAND_NM)
  @javax.annotation.Nullable
  private String brandNm;

  public static final String SERIALIZED_NAME_BRAND_SERVICE_GUIDE = "brandServiceGuide";
  @SerializedName(SERIALIZED_NAME_BRAND_SERVICE_GUIDE)
  @javax.annotation.Nullable
  private String brandServiceGuide;

  public static final String SERIALIZED_NAME_PRICE = "price";
  @SerializedName(SERIALIZED_NAME_PRICE)
  @javax.annotation.Nullable
  private PRODUCTPRICESCHEMA price;

  public static final String SERIALIZED_NAME_PRODUCT_DESC = "productDesc";
  @SerializedName(SERIALIZED_NAME_PRODUCT_DESC)
  @javax.annotation.Nullable
  private String productDesc;

  public static final String SERIALIZED_NAME_TERMS = "terms";
  @SerializedName(SERIALIZED_NAME_TERMS)
  @javax.annotation.Nullable
  private String terms;

  public static final String SERIALIZED_NAME_STORE_LIST = "storeList";
  @SerializedName(SERIALIZED_NAME_STORE_LIST)
  @javax.annotation.Nullable
  private List<STOREPRODUCTSCHEMA> storeList = new ArrayList<>();

  public static final String SERIALIZED_NAME_TOTAL_STORE = "totalStore";
  @SerializedName(SERIALIZED_NAME_TOTAL_STORE)
  @javax.annotation.Nullable
  private Integer totalStore;

  public static final String SERIALIZED_NAME_STORE_PAGINATION = "storePagination";
  @SerializedName(SERIALIZED_NAME_STORE_PAGINATION)
  @javax.annotation.Nullable
  private STOREPAGINGSCHEMA storePagination;

  public PRODUCTSVOUCHERCHECK() {
  }

  public PRODUCTSVOUCHERCHECK productId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
    return this;
  }

  /**
   * Product Id
   * @return productId
   */
  @javax.annotation.Nullable
  public Integer getProductId() {
    return productId;
  }

  public void setProductId(@javax.annotation.Nullable Integer productId) {
    this.productId = productId;
  }


  public PRODUCTSVOUCHERCHECK productNm(@javax.annotation.Nullable String productNm) {
    this.productNm = productNm;
    return this;
  }

  /**
   * Product Name
   * @return productNm
   */
  @javax.annotation.Nullable
  public String getProductNm() {
    return productNm;
  }

  public void setProductNm(@javax.annotation.Nullable String productNm) {
    this.productNm = productNm;
  }


  public PRODUCTSVOUCHERCHECK productImg(@javax.annotation.Nullable String productImg) {
    this.productImg = productImg;
    return this;
  }

  /**
   * Link product image
   * @return productImg
   */
  @javax.annotation.Nullable
  public String getProductImg() {
    return productImg;
  }

  public void setProductImg(@javax.annotation.Nullable String productImg) {
    this.productImg = productImg;
  }


  public PRODUCTSVOUCHERCHECK brandId(@javax.annotation.Nullable Integer brandId) {
    this.brandId = brandId;
    return this;
  }

  /**
   * Brand id
   * @return brandId
   */
  @javax.annotation.Nullable
  public Integer getBrandId() {
    return brandId;
  }

  public void setBrandId(@javax.annotation.Nullable Integer brandId) {
    this.brandId = brandId;
  }


  public PRODUCTSVOUCHERCHECK brandNm(@javax.annotation.Nullable String brandNm) {
    this.brandNm = brandNm;
    return this;
  }

  /**
   * Brand name
   * @return brandNm
   */
  @javax.annotation.Nullable
  public String getBrandNm() {
    return brandNm;
  }

  public void setBrandNm(@javax.annotation.Nullable String brandNm) {
    this.brandNm = brandNm;
  }


  public PRODUCTSVOUCHERCHECK brandServiceGuide(@javax.annotation.Nullable String brandServiceGuide) {
    this.brandServiceGuide = brandServiceGuide;
    return this;
  }

  /**
   * Get brandServiceGuide
   * @return brandServiceGuide
   */
  @javax.annotation.Nullable
  public String getBrandServiceGuide() {
    return brandServiceGuide;
  }

  public void setBrandServiceGuide(@javax.annotation.Nullable String brandServiceGuide) {
    this.brandServiceGuide = brandServiceGuide;
  }


  public PRODUCTSVOUCHERCHECK price(@javax.annotation.Nullable PRODUCTPRICESCHEMA price) {
    this.price = price;
    return this;
  }

  /**
   * Get price
   * @return price
   */
  @javax.annotation.Nullable
  public PRODUCTPRICESCHEMA getPrice() {
    return price;
  }

  public void setPrice(@javax.annotation.Nullable PRODUCTPRICESCHEMA price) {
    this.price = price;
  }


  public PRODUCTSVOUCHERCHECK productDesc(@javax.annotation.Nullable String productDesc) {
    this.productDesc = productDesc;
    return this;
  }

  /**
   * Get productDesc
   * @return productDesc
   */
  @javax.annotation.Nullable
  public String getProductDesc() {
    return productDesc;
  }

  public void setProductDesc(@javax.annotation.Nullable String productDesc) {
    this.productDesc = productDesc;
  }


  public PRODUCTSVOUCHERCHECK terms(@javax.annotation.Nullable String terms) {
    this.terms = terms;
    return this;
  }

  /**
   * Get terms
   * @return terms
   */
  @javax.annotation.Nullable
  public String getTerms() {
    return terms;
  }

  public void setTerms(@javax.annotation.Nullable String terms) {
    this.terms = terms;
  }


  public PRODUCTSVOUCHERCHECK storeList(@javax.annotation.Nullable List<STOREPRODUCTSCHEMA> storeList) {
    this.storeList = storeList;
    return this;
  }

  public PRODUCTSVOUCHERCHECK addStoreListItem(STOREPRODUCTSCHEMA storeListItem) {
    if (this.storeList == null) {
      this.storeList = new ArrayList<>();
    }
    this.storeList.add(storeListItem);
    return this;
  }

  /**
   * Get storeList
   * @return storeList
   */
  @javax.annotation.Nullable
  public List<STOREPRODUCTSCHEMA> getStoreList() {
    return storeList;
  }

  public void setStoreList(@javax.annotation.Nullable List<STOREPRODUCTSCHEMA> storeList) {
    this.storeList = storeList;
  }


  public PRODUCTSVOUCHERCHECK totalStore(@javax.annotation.Nullable Integer totalStore) {
    this.totalStore = totalStore;
    return this;
  }

  /**
   * Get totalStore
   * @return totalStore
   */
  @javax.annotation.Nullable
  public Integer getTotalStore() {
    return totalStore;
  }

  public void setTotalStore(@javax.annotation.Nullable Integer totalStore) {
    this.totalStore = totalStore;
  }


  public PRODUCTSVOUCHERCHECK storePagination(@javax.annotation.Nullable STOREPAGINGSCHEMA storePagination) {
    this.storePagination = storePagination;
    return this;
  }

  /**
   * Get storePagination
   * @return storePagination
   */
  @javax.annotation.Nullable
  public STOREPAGINGSCHEMA getStorePagination() {
    return storePagination;
  }

  public void setStorePagination(@javax.annotation.Nullable STOREPAGINGSCHEMA storePagination) {
    this.storePagination = storePagination;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PRODUCTSVOUCHERCHECK PRODUCTS_VOUCHER_CHECK = (PRODUCTSVOUCHERCHECK) o;
    return Objects.equals(this.productId, PRODUCTS_VOUCHER_CHECK.productId) &&
        Objects.equals(this.productNm, PRODUCTS_VOUCHER_CHECK.productNm) &&
        Objects.equals(this.productImg, PRODUCTS_VOUCHER_CHECK.productImg) &&
        Objects.equals(this.brandId, PRODUCTS_VOUCHER_CHECK.brandId) &&
        Objects.equals(this.brandNm, PRODUCTS_VOUCHER_CHECK.brandNm) &&
        Objects.equals(this.brandServiceGuide, PRODUCTS_VOUCHER_CHECK.brandServiceGuide) &&
        Objects.equals(this.price, PRODUCTS_VOUCHER_CHECK.price) &&
        Objects.equals(this.productDesc, PRODUCTS_VOUCHER_CHECK.productDesc) &&
        Objects.equals(this.terms, PRODUCTS_VOUCHER_CHECK.terms) &&
        Objects.equals(this.storeList, PRODUCTS_VOUCHER_CHECK.storeList) &&
        Objects.equals(this.totalStore, PRODUCTS_VOUCHER_CHECK.totalStore) &&
        Objects.equals(this.storePagination, PRODUCTS_VOUCHER_CHECK.storePagination);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(productId, productNm, productImg, brandId, brandNm, brandServiceGuide, price, productDesc, terms, storeList, totalStore, storePagination);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PRODUCTSVOUCHERCHECK {\n");
    sb.append("    productId: ").append(toIndentedString(productId)).append("\n");
    sb.append("    productNm: ").append(toIndentedString(productNm)).append("\n");
    sb.append("    productImg: ").append(toIndentedString(productImg)).append("\n");
    sb.append("    brandId: ").append(toIndentedString(brandId)).append("\n");
    sb.append("    brandNm: ").append(toIndentedString(brandNm)).append("\n");
    sb.append("    brandServiceGuide: ").append(toIndentedString(brandServiceGuide)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("    productDesc: ").append(toIndentedString(productDesc)).append("\n");
    sb.append("    terms: ").append(toIndentedString(terms)).append("\n");
    sb.append("    storeList: ").append(toIndentedString(storeList)).append("\n");
    sb.append("    totalStore: ").append(toIndentedString(totalStore)).append("\n");
    sb.append("    storePagination: ").append(toIndentedString(storePagination)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("productId");
    openapiFields.add("productNm");
    openapiFields.add("productImg");
    openapiFields.add("brandId");
    openapiFields.add("brandNm");
    openapiFields.add("brandServiceGuide");
    openapiFields.add("price");
    openapiFields.add("productDesc");
    openapiFields.add("terms");
    openapiFields.add("storeList");
    openapiFields.add("totalStore");
    openapiFields.add("storePagination");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to PRODUCTSVOUCHERCHECK
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!PRODUCTSVOUCHERCHECK.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in PRODUCTSVOUCHERCHECK is not found in the empty JSON string", PRODUCTSVOUCHERCHECK.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!PRODUCTSVOUCHERCHECK.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `PRODUCTSVOUCHERCHECK` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("productNm") != null && !jsonObj.get("productNm").isJsonNull()) && !jsonObj.get("productNm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productNm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productNm").toString()));
      }
      if ((jsonObj.get("productImg") != null && !jsonObj.get("productImg").isJsonNull()) && !jsonObj.get("productImg").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productImg` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productImg").toString()));
      }
      if ((jsonObj.get("brandNm") != null && !jsonObj.get("brandNm").isJsonNull()) && !jsonObj.get("brandNm").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandNm` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandNm").toString()));
      }
      if ((jsonObj.get("brandServiceGuide") != null && !jsonObj.get("brandServiceGuide").isJsonNull()) && !jsonObj.get("brandServiceGuide").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `brandServiceGuide` to be a primitive type in the JSON string but got `%s`", jsonObj.get("brandServiceGuide").toString()));
      }
      // validate the optional field `price`
      if (jsonObj.get("price") != null && !jsonObj.get("price").isJsonNull()) {
        PRODUCTPRICESCHEMA.validateJsonElement(jsonObj.get("price"));
      }
      if ((jsonObj.get("productDesc") != null && !jsonObj.get("productDesc").isJsonNull()) && !jsonObj.get("productDesc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `productDesc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("productDesc").toString()));
      }
      if ((jsonObj.get("terms") != null && !jsonObj.get("terms").isJsonNull()) && !jsonObj.get("terms").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `terms` to be a primitive type in the JSON string but got `%s`", jsonObj.get("terms").toString()));
      }
      if (jsonObj.get("storeList") != null && !jsonObj.get("storeList").isJsonNull()) {
        JsonArray jsonArraystoreList = jsonObj.getAsJsonArray("storeList");
        if (jsonArraystoreList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("storeList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `storeList` to be an array in the JSON string but got `%s`", jsonObj.get("storeList").toString()));
          }

          // validate the optional field `storeList` (array)
          for (int i = 0; i < jsonArraystoreList.size(); i++) {
            STOREPRODUCTSCHEMA.validateJsonElement(jsonArraystoreList.get(i));
          };
        }
      }
      // validate the optional field `storePagination`
      if (jsonObj.get("storePagination") != null && !jsonObj.get("storePagination").isJsonNull()) {
        STOREPAGINGSCHEMA.validateJsonElement(jsonObj.get("storePagination"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!PRODUCTSVOUCHERCHECK.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'PRODUCTSVOUCHERCHECK' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<PRODUCTSVOUCHERCHECK> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(PRODUCTSVOUCHERCHECK.class));

       return (TypeAdapter<T>) new TypeAdapter<PRODUCTSVOUCHERCHECK>() {
           @Override
           public void write(JsonWriter out, PRODUCTSVOUCHERCHECK value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public PRODUCTSVOUCHERCHECK read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of PRODUCTSVOUCHERCHECK given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of PRODUCTSVOUCHERCHECK
   * @throws IOException if the JSON string is invalid with respect to PRODUCTSVOUCHERCHECK
   */
  public static PRODUCTSVOUCHERCHECK fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, PRODUCTSVOUCHERCHECK.class);
  }

  /**
   * Convert an instance of PRODUCTSVOUCHERCHECK to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

