/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.STORESSCHEMA;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gotit.sdk.JSON;

/**
 * STORESRESPONSEDataInner
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T09:04:05.866297444Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class STORESRESPONSEDataInner {
  public static final String SERIALIZED_NAME_STORE_LIST = "storeList";
  @SerializedName(SERIALIZED_NAME_STORE_LIST)
  @javax.annotation.Nullable
  private List<STORESSCHEMA> storeList = new ArrayList<>();

  public STORESRESPONSEDataInner() {
  }

  public STORESRESPONSEDataInner storeList(@javax.annotation.Nullable List<STORESSCHEMA> storeList) {
    this.storeList = storeList;
    return this;
  }

  public STORESRESPONSEDataInner addStoreListItem(STORESSCHEMA storeListItem) {
    if (this.storeList == null) {
      this.storeList = new ArrayList<>();
    }
    this.storeList.add(storeListItem);
    return this;
  }

  /**
   * Get storeList
   * @return storeList
   */
  @javax.annotation.Nullable
  public List<STORESSCHEMA> getStoreList() {
    return storeList;
  }

  public void setStoreList(@javax.annotation.Nullable List<STORESSCHEMA> storeList) {
    this.storeList = storeList;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    STORESRESPONSEDataInner stORESRESPONSEDataInner = (STORESRESPONSEDataInner) o;
    return Objects.equals(this.storeList, stORESRESPONSEDataInner.storeList);
  }

  @Override
  public int hashCode() {
    return Objects.hash(storeList);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class STORESRESPONSEDataInner {\n");
    sb.append("    storeList: ").append(toIndentedString(storeList)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("storeList");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to STORESRESPONSEDataInner
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!STORESRESPONSEDataInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in STORESRESPONSEDataInner is not found in the empty JSON string", STORESRESPONSEDataInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!STORESRESPONSEDataInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `STORESRESPONSEDataInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if (jsonObj.get("storeList") != null && !jsonObj.get("storeList").isJsonNull()) {
        JsonArray jsonArraystoreList = jsonObj.getAsJsonArray("storeList");
        if (jsonArraystoreList != null) {
          // ensure the json data is an array
          if (!jsonObj.get("storeList").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `storeList` to be an array in the JSON string but got `%s`", jsonObj.get("storeList").toString()));
          }

          // validate the optional field `storeList` (array)
          for (int i = 0; i < jsonArraystoreList.size(); i++) {
            STORESSCHEMA.validateJsonElement(jsonArraystoreList.get(i));
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!STORESRESPONSEDataInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'STORESRESPONSEDataInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<STORESRESPONSEDataInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(STORESRESPONSEDataInner.class));

       return (TypeAdapter<T>) new TypeAdapter<STORESRESPONSEDataInner>() {
           @Override
           public void write(JsonWriter out, STORESRESPONSEDataInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public STORESRESPONSEDataInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of STORESRESPONSEDataInner given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of STORESRESPONSEDataInner
   * @throws IOException if the JSON string is invalid with respect to STORESRESPONSEDataInner
   */
  public static STORESRESPONSEDataInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, STORESRESPONSEDataInner.class);
  }

  /**
   * Convert an instance of STORESRESPONSEDataInner to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

