/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.jackson.nullable.JsonNullable;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import com.gotit.sdk.JSON;

/**
 * VOUCHERESCHEMA
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T09:04:05.866297444Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class VOUCHERESCHEMA {
  public static final String SERIALIZED_NAME_VOUCHER_LINK = "voucher_link";
  @SerializedName(SERIALIZED_NAME_VOUCHER_LINK)
  @javax.annotation.Nullable
  private String voucherLink;

  public static final String SERIALIZED_NAME_VOUCHER_COVER_LINK = "voucher_cover_link";
  @SerializedName(SERIALIZED_NAME_VOUCHER_COVER_LINK)
  @javax.annotation.Nullable
  private String voucherCoverLink;

  public static final String SERIALIZED_NAME_VOUCHER_SERIAL = "voucher_serial";
  @SerializedName(SERIALIZED_NAME_VOUCHER_SERIAL)
  @javax.annotation.Nullable
  private String voucherSerial;

  public static final String SERIALIZED_NAME_VALUE = "value";
  @SerializedName(SERIALIZED_NAME_VALUE)
  @javax.annotation.Nullable
  private String value;

  public static final String SERIALIZED_NAME_EXPIRED_DATE = "expired_date";
  @SerializedName(SERIALIZED_NAME_EXPIRED_DATE)
  @javax.annotation.Nullable
  private String expiredDate;

  public VOUCHERESCHEMA() {
  }

  public VOUCHERESCHEMA voucherLink(@javax.annotation.Nullable String voucherLink) {
    this.voucherLink = voucherLink;
    return this;
  }

  /**
   * Voucher of link e
   * @return voucherLink
   */
  @javax.annotation.Nullable
  public String getVoucherLink() {
    return voucherLink;
  }

  public void setVoucherLink(@javax.annotation.Nullable String voucherLink) {
    this.voucherLink = voucherLink;
  }


  public VOUCHERESCHEMA voucherCoverLink(@javax.annotation.Nullable String voucherCoverLink) {
    this.voucherCoverLink = voucherCoverLink;
    return this;
  }

  /**
   * Voucher cover of link e
   * @return voucherCoverLink
   */
  @javax.annotation.Nullable
  public String getVoucherCoverLink() {
    return voucherCoverLink;
  }

  public void setVoucherCoverLink(@javax.annotation.Nullable String voucherCoverLink) {
    this.voucherCoverLink = voucherCoverLink;
  }


  public VOUCHERESCHEMA voucherSerial(@javax.annotation.Nullable String voucherSerial) {
    this.voucherSerial = voucherSerial;
    return this;
  }

  /**
   * Voucher serial of link e
   * @return voucherSerial
   */
  @javax.annotation.Nullable
  public String getVoucherSerial() {
    return voucherSerial;
  }

  public void setVoucherSerial(@javax.annotation.Nullable String voucherSerial) {
    this.voucherSerial = voucherSerial;
  }


  public VOUCHERESCHEMA value(@javax.annotation.Nullable String value) {
    this.value = value;
    return this;
  }

  /**
   * Voucher value of link e
   * @return value
   */
  @javax.annotation.Nullable
  public String getValue() {
    return value;
  }

  public void setValue(@javax.annotation.Nullable String value) {
    this.value = value;
  }


  public VOUCHERESCHEMA expiredDate(@javax.annotation.Nullable String expiredDate) {
    this.expiredDate = expiredDate;
    return this;
  }

  /**
   * Expiry date of voucher link Format: &#39;YYYY-MM-DD&#39;
   * @return expiredDate
   */
  @javax.annotation.Nullable
  public String getExpiredDate() {
    return expiredDate;
  }

  public void setExpiredDate(@javax.annotation.Nullable String expiredDate) {
    this.expiredDate = expiredDate;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VOUCHERESCHEMA VOUCHER_E_SCHEMA = (VOUCHERESCHEMA) o;
    return Objects.equals(this.voucherLink, VOUCHER_E_SCHEMA.voucherLink) &&
        Objects.equals(this.voucherCoverLink, VOUCHER_E_SCHEMA.voucherCoverLink) &&
        Objects.equals(this.voucherSerial, VOUCHER_E_SCHEMA.voucherSerial) &&
        Objects.equals(this.value, VOUCHER_E_SCHEMA.value) &&
        Objects.equals(this.expiredDate, VOUCHER_E_SCHEMA.expiredDate);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(voucherLink, voucherCoverLink, voucherSerial, value, expiredDate);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VOUCHERESCHEMA {\n");
    sb.append("    voucherLink: ").append(toIndentedString(voucherLink)).append("\n");
    sb.append("    voucherCoverLink: ").append(toIndentedString(voucherCoverLink)).append("\n");
    sb.append("    voucherSerial: ").append(toIndentedString(voucherSerial)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    expiredDate: ").append(toIndentedString(expiredDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("voucher_link");
    openapiFields.add("voucher_cover_link");
    openapiFields.add("voucher_serial");
    openapiFields.add("value");
    openapiFields.add("expired_date");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

  /**
   * Validates the JSON Element and throws an exception if issues found
   *
   * @param jsonElement JSON Element
   * @throws IOException if the JSON Element is invalid with respect to VOUCHERESCHEMA
   */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!VOUCHERESCHEMA.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in VOUCHERESCHEMA is not found in the empty JSON string", VOUCHERESCHEMA.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!VOUCHERESCHEMA.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `VOUCHERESCHEMA` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("voucher_link") != null && !jsonObj.get("voucher_link").isJsonNull()) && !jsonObj.get("voucher_link").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucher_link` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucher_link").toString()));
      }
      if ((jsonObj.get("voucher_cover_link") != null && !jsonObj.get("voucher_cover_link").isJsonNull()) && !jsonObj.get("voucher_cover_link").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucher_cover_link` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucher_cover_link").toString()));
      }
      if ((jsonObj.get("voucher_serial") != null && !jsonObj.get("voucher_serial").isJsonNull()) && !jsonObj.get("voucher_serial").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `voucher_serial` to be a primitive type in the JSON string but got `%s`", jsonObj.get("voucher_serial").toString()));
      }
      if ((jsonObj.get("value") != null && !jsonObj.get("value").isJsonNull()) && !jsonObj.get("value").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `value` to be a primitive type in the JSON string but got `%s`", jsonObj.get("value").toString()));
      }
      if ((jsonObj.get("expired_date") != null && !jsonObj.get("expired_date").isJsonNull()) && !jsonObj.get("expired_date").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `expired_date` to be a primitive type in the JSON string but got `%s`", jsonObj.get("expired_date").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!VOUCHERESCHEMA.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'VOUCHERESCHEMA' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<VOUCHERESCHEMA> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(VOUCHERESCHEMA.class));

       return (TypeAdapter<T>) new TypeAdapter<VOUCHERESCHEMA>() {
           @Override
           public void write(JsonWriter out, VOUCHERESCHEMA value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public VOUCHERESCHEMA read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

  /**
   * Create an instance of VOUCHERESCHEMA given an JSON string
   *
   * @param jsonString JSON string
   * @return An instance of VOUCHERESCHEMA
   * @throws IOException if the JSON string is invalid with respect to VOUCHERESCHEMA
   */
  public static VOUCHERESCHEMA fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, VOUCHERESCHEMA.class);
  }

  /**
   * Convert an instance of VOUCHERESCHEMA to an JSON string
   *
   * @return JSON string
   */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

