/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.gotit.sdk.model.PRODUCTPRICESCHEMA;
import com.gotit.sdk.model.PRODUCTV;
import com.gotit.sdk.model.STOREPRODUCTSCHEMA;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.jackson.nullable.JsonNullable;



import java.io.IOException;
import java.lang.reflect.Type;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapter;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.JsonPrimitive;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonSerializationContext;
import com.google.gson.JsonSerializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonArray;
import com.google.gson.JsonParseException;

import com.gotit.sdk.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-05-05T09:04:05.866297444Z[Etc/UTC]", comments = "Generator version: 7.12.0")
public class VOUCHERVSCHEMAProduct extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(VOUCHERVSCHEMAProduct.class.getName());

    public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
        @SuppressWarnings("unchecked")
        @Override
        public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
            if (!VOUCHERVSCHEMAProduct.class.isAssignableFrom(type.getRawType())) {
                return null; // this class only serializes 'VOUCHERVSCHEMAProduct' and its subtypes
            }
            final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
            final TypeAdapter<PRODUCTV> adapterPRODUCTV = gson.getDelegateAdapter(this, TypeToken.get(PRODUCTV.class));

            return (TypeAdapter<T>) new TypeAdapter<VOUCHERVSCHEMAProduct>() {
                @Override
                public void write(JsonWriter out, VOUCHERVSCHEMAProduct value) throws IOException {
                    if (value == null || value.getActualInstance() == null) {
                        elementAdapter.write(out, null);
                        return;
                    }

                    // check if the actual instance is of the type `PRODUCTV`
                    if (value.getActualInstance() instanceof PRODUCTV) {
                        JsonElement element = adapterPRODUCTV.toJsonTree((PRODUCTV)value.getActualInstance());
                        elementAdapter.write(out, element);
                        return;
                    }
                    throw new IOException("Failed to serialize as the type doesn't match oneOf schemas: PRODUCTV");
                }

                @Override
                public VOUCHERVSCHEMAProduct read(JsonReader in) throws IOException {
                    Object deserialized = null;
                    JsonElement jsonElement = elementAdapter.read(in);

                    int match = 0;
                    ArrayList<String> errorMessages = new ArrayList<>();
                    TypeAdapter actualAdapter = elementAdapter;

                    // deserialize PRODUCTV
                    try {
                        // validate the JSON object to see if any exception is thrown
                        PRODUCTV.validateJsonElement(jsonElement);
                        actualAdapter = adapterPRODUCTV;
                        match++;
                        log.log(Level.FINER, "Input data matches schema 'PRODUCTV'");
                    } catch (Exception e) {
                        // deserialization failed, continue
                        errorMessages.add(String.format("Deserialization for PRODUCTV failed with `%s`.", e.getMessage()));
                        log.log(Level.FINER, "Input data does not match schema 'PRODUCTV'", e);
                    }

                    if (match == 1) {
                        VOUCHERVSCHEMAProduct ret = new VOUCHERVSCHEMAProduct();
                        ret.setActualInstance(actualAdapter.fromJsonTree(jsonElement));
                        return ret;
                    }

                    throw new IOException(String.format("Failed deserialization for VOUCHERVSCHEMAProduct: %d classes match result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", match, errorMessages, jsonElement.toString()));
                }
            }.nullSafe();
        }
    }

    // store a list of schema names defined in oneOf
    public static final Map<String, Class<?>> schemas = new HashMap<String, Class<?>>();

    public VOUCHERVSCHEMAProduct() {
        super("oneOf", Boolean.TRUE);
    }

    public VOUCHERVSCHEMAProduct(Object o) {
        super("oneOf", Boolean.TRUE);
        setActualInstance(o);
    }

    static {
        schemas.put("PRODUCTV", PRODUCTV.class);
    }

    @Override
    public Map<String, Class<?>> getSchemas() {
        return VOUCHERVSCHEMAProduct.schemas;
    }

    /**
     * Set the instance that matches the oneOf child schema, check
     * the instance parameter is valid against the oneOf child schemas:
     * PRODUCTV
     *
     * It could be an instance of the 'oneOf' schemas.
     */
    @Override
    public void setActualInstance(Object instance) {
        if (instance == null) {
           super.setActualInstance(instance);
           return;
        }

        if (instance instanceof PRODUCTV) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be PRODUCTV");
    }

    /**
     * Get the actual instance, which can be the following:
     * PRODUCTV
     *
     * @return The actual instance (PRODUCTV)
     */
    @SuppressWarnings("unchecked")
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `PRODUCTV`. If the actual instance is not `PRODUCTV`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `PRODUCTV`
     * @throws ClassCastException if the instance is not `PRODUCTV`
     */
    public PRODUCTV getPRODUCTV() throws ClassCastException {
        return (PRODUCTV)super.getActualInstance();
    }

    /**
     * Validates the JSON Element and throws an exception if issues found
     *
     * @param jsonElement JSON Element
     * @throws IOException if the JSON Element is invalid with respect to VOUCHERVSCHEMAProduct
     */
    public static void validateJsonElement(JsonElement jsonElement) throws IOException {
        // validate oneOf schemas one by one
        int validCount = 0;
        ArrayList<String> errorMessages = new ArrayList<>();
        // validate the json string with PRODUCTV
        try {
            PRODUCTV.validateJsonElement(jsonElement);
            validCount++;
        } catch (Exception e) {
            errorMessages.add(String.format("Deserialization for PRODUCTV failed with `%s`.", e.getMessage()));
            // continue to the next one
        }
        if (validCount != 1) {
            throw new IOException(String.format("The JSON string is invalid for VOUCHERVSCHEMAProduct with oneOf schemas: PRODUCTV. %d class(es) match the result, expected 1. Detailed failure message for oneOf schemas: %s. JSON: %s", validCount, errorMessages, jsonElement.toString()));
        }
    }

    /**
     * Create an instance of VOUCHERVSCHEMAProduct given an JSON string
     *
     * @param jsonString JSON string
     * @return An instance of VOUCHERVSCHEMAProduct
     * @throws IOException if the JSON string is invalid with respect to VOUCHERVSCHEMAProduct
     */
    public static VOUCHERVSCHEMAProduct fromJson(String jsonString) throws IOException {
        return JSON.getGson().fromJson(jsonString, VOUCHERVSCHEMAProduct.class);
    }

    /**
     * Convert an instance of VOUCHERVSCHEMAProduct to an JSON string
     *
     * @return JSON string
     */
    public String toJson() {
        return JSON.getGson().toJson(this);
    }
}

