/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.api;

import com.gotit.sdk.ApiException;
import com.gotit.sdk.model.BRANDDETAILRESPONSE;
import com.gotit.sdk.model.BRANDSRESPONSE;
import com.gotit.sdk.model.HTTPBADREQUEST;
import com.gotit.sdk.model.HTTPINTERNALSERVERERROR;
import com.gotit.sdk.model.HTTPNOTFOUND;
import com.gotit.sdk.model.HTTPUNAUTHORIZED;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BrandsApi
 */
@Disabled
public class BrandsApiTest {

    private final BrandsApi api = new BrandsApi();

    /**
     * Get brand by product
     *
     * Returns brand detail data master
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void brandsByProductsTest() throws ApiException {
        String xGIAuthorization = null;
        BRANDDETAILRESPONSE response = api.brandsByProducts(xGIAuthorization);
        // TODO: test validations
    }

    /**
     * Get brand detail
     *
     * Returns brand detail data master
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getDetailOfBrandTest() throws ApiException {
        String xGIAuthorization = null;
        Integer id = null;
        BRANDDETAILRESPONSE response = api.getDetailOfBrand(xGIAuthorization, id);
        // TODO: test validations
    }

    /**
     * Get list of brands
     *
     * Retrieve a list of brands
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getListOfBrandsTest() throws ApiException {
        String xGIAuthorization = null;
        BRANDSRESPONSE response = api.getListOfBrands(xGIAuthorization);
        // TODO: test validations
    }

}
