/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.api;

import com.gotit.sdk.ApiException;
import com.gotit.sdk.model.HTTPBADREQUEST;
import com.gotit.sdk.model.HTTPINTERNALSERVERERROR;
import com.gotit.sdk.model.HTTPNOTFOUND;
import com.gotit.sdk.model.HTTPUNAUTHORIZED;
import com.gotit.sdk.model.REQUESTCHECKSTATUSZNS;
import com.gotit.sdk.model.REQUESTSENDVOUCHERBYEMAIL;
import com.gotit.sdk.model.REQUESTSENDVOUCHERBYSMS;
import com.gotit.sdk.model.REQUESTSENDVOUCHERBYZNS;
import com.gotit.sdk.model.VOUCHERCHECKZNSRESPONSE;
import com.gotit.sdk.model.VOUCHERSENDEMAILRESPONSE;
import com.gotit.sdk.model.VOUCHERSENDSMSRESPONSE;
import com.gotit.sdk.model.VOUCHERSENDZNSRESPONSE;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for VoucherSendMethodApi
 */
@Disabled
public class VoucherSendMethodApiTest {

    private final VoucherSendMethodApi api = new VoucherSendMethodApi();

    /**
     * Check status zns
     *
     * Check status zns
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void checkStatusZNSTest() throws ApiException {
        String xGIAuthorization = null;
        REQUESTCHECKSTATUSZNS REQUESTCHECKSTATUSZNS = null;
        VOUCHERCHECKZNSRESPONSE response = api.checkStatusZNS(xGIAuthorization, REQUESTCHECKSTATUSZNS);
        // TODO: test validations
    }

    /**
     * Send voucher by mail
     *
     * Send voucher by mail
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendVoucherByEmailTest() throws ApiException {
        String xGIAuthorization = null;
        REQUESTSENDVOUCHERBYEMAIL REQUESTSENDVOUCHERBYEMAIL = null;
        VOUCHERSENDEMAILRESPONSE response = api.sendVoucherByEmail(xGIAuthorization, REQUESTSENDVOUCHERBYEMAIL);
        // TODO: test validations
    }

    /**
     * Send voucher by sms
     *
     * Send voucher by sms
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendVoucherBySMSTest() throws ApiException {
        String xGIAuthorization = null;
        REQUESTSENDVOUCHERBYSMS REQUESTSENDVOUCHERBYSMS = null;
        VOUCHERSENDSMSRESPONSE response = api.sendVoucherBySMS(xGIAuthorization, REQUESTSENDVOUCHERBYSMS);
        // TODO: test validations
    }

    /**
     * Send voucher by zns
     *
     * Send voucher by zns
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void sendVoucherByZNSTest() throws ApiException {
        String xGIAuthorization = null;
        REQUESTSENDVOUCHERBYZNS REQUESTSENDVOUCHERBYZNS = null;
        VOUCHERSENDZNSRESPONSE response = api.sendVoucherByZNS(xGIAuthorization, REQUESTSENDVOUCHERBYZNS);
        // TODO: test validations
    }

}
