/*
 * Sample API
 * Technical document APIs for API Version 4.
 *
 * The version of the OpenAPI document: 4.0.0
 * Contact: quang.huynh@gotit.vn
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.gotit.sdk.api;

import com.gotit.sdk.ApiCallback;
import com.gotit.sdk.ApiClient;
import com.gotit.sdk.ApiException;
import com.gotit.sdk.ApiResponse;
import com.gotit.sdk.Configuration;
import com.gotit.sdk.Pair;
import com.gotit.sdk.ProgressRequestBody;
import com.gotit.sdk.ProgressResponseBody;

import com.google.gson.reflect.TypeToken;

import java.io.IOException;


import com.gotit.sdk.model.CATEGORIESRESPONSE;
import com.gotit.sdk.model.HTTPBADREQUEST;
import com.gotit.sdk.model.HTTPINTERNALSERVERERROR;
import com.gotit.sdk.model.HTTPNOTFOUND;
import com.gotit.sdk.model.HTTPUNAUTHORIZED;

import java.lang.reflect.Type;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

public class CategoriesApi {
    private ApiClient localVarApiClient;
    private int localHostIndex;
    private String localCustomBaseUrl;

    public CategoriesApi() {
        this(Configuration.getDefaultApiClient());
    }

    public CategoriesApi(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public ApiClient getApiClient() {
        return localVarApiClient;
    }

    public void setApiClient(ApiClient apiClient) {
        this.localVarApiClient = apiClient;
    }

    public int getHostIndex() {
        return localHostIndex;
    }

    public void setHostIndex(int hostIndex) {
        this.localHostIndex = hostIndex;
    }

    public String getCustomBaseUrl() {
        return localCustomBaseUrl;
    }

    public void setCustomBaseUrl(String customBaseUrl) {
        this.localCustomBaseUrl = customBaseUrl;
    }

    /**
     * Build call for getCategoryByProduct
     * @param xGIAuthorization Authorization (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCategoryByProductCall(String xGIAuthorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v4.0/categories/categoriesByProducts";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xGIAuthorization != null) {
            localVarHeaderParams.put("X-GI-Authorization", localVarApiClient.parameterToString(xGIAuthorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getCategoryByProductValidateBeforeCall(String xGIAuthorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xGIAuthorization' is set
        if (xGIAuthorization == null) {
            throw new ApiException("Missing the required parameter 'xGIAuthorization' when calling getCategoryByProduct(Async)");
        }

        return getCategoryByProductCall(xGIAuthorization, _callback);

    }

    /**
     * Get category by product
     * Returns all categories data master
     * @param xGIAuthorization Authorization (required)
     * @return CATEGORIESRESPONSE
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public CATEGORIESRESPONSE getCategoryByProduct(String xGIAuthorization) throws ApiException {
        ApiResponse<CATEGORIESRESPONSE> localVarResp = getCategoryByProductWithHttpInfo(xGIAuthorization);
        return localVarResp.getData();
    }

    /**
     * Get category by product
     * Returns all categories data master
     * @param xGIAuthorization Authorization (required)
     * @return ApiResponse&lt;CATEGORIESRESPONSE&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CATEGORIESRESPONSE> getCategoryByProductWithHttpInfo(String xGIAuthorization) throws ApiException {
        okhttp3.Call localVarCall = getCategoryByProductValidateBeforeCall(xGIAuthorization, null);
        Type localVarReturnType = new TypeToken<CATEGORIESRESPONSE>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get category by product (asynchronously)
     * Returns all categories data master
     * @param xGIAuthorization Authorization (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getCategoryByProductAsync(String xGIAuthorization, final ApiCallback<CATEGORIESRESPONSE> _callback) throws ApiException {

        okhttp3.Call localVarCall = getCategoryByProductValidateBeforeCall(xGIAuthorization, _callback);
        Type localVarReturnType = new TypeToken<CATEGORIESRESPONSE>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
    /**
     * Build call for getListOfCategories
     * @param xGIAuthorization Authorization (required)
     * @param _callback Callback for upload/download progress
     * @return Call to execute
     * @throws ApiException If fail to serialize the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getListOfCategoriesCall(String xGIAuthorization, final ApiCallback _callback) throws ApiException {
        String basePath = null;
        // Operation Servers
        String[] localBasePaths = new String[] {  };

        // Determine Base Path to Use
        if (localCustomBaseUrl != null){
            basePath = localCustomBaseUrl;
        } else if ( localBasePaths.length > 0 ) {
            basePath = localBasePaths[localHostIndex];
        } else {
            basePath = null;
        }

        Object localVarPostBody = null;

        // create path and map variables
        String localVarPath = "/api/v4.0/categories";

        List<Pair> localVarQueryParams = new ArrayList<Pair>();
        List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
        Map<String, String> localVarHeaderParams = new HashMap<String, String>();
        Map<String, String> localVarCookieParams = new HashMap<String, String>();
        Map<String, Object> localVarFormParams = new HashMap<String, Object>();

        final String[] localVarAccepts = {
            "application/json"
        };
        final String localVarAccept = localVarApiClient.selectHeaderAccept(localVarAccepts);
        if (localVarAccept != null) {
            localVarHeaderParams.put("Accept", localVarAccept);
        }

        final String[] localVarContentTypes = {
        };
        final String localVarContentType = localVarApiClient.selectHeaderContentType(localVarContentTypes);
        if (localVarContentType != null) {
            localVarHeaderParams.put("Content-Type", localVarContentType);
        }

        if (xGIAuthorization != null) {
            localVarHeaderParams.put("X-GI-Authorization", localVarApiClient.parameterToString(xGIAuthorization));
        }


        String[] localVarAuthNames = new String[] {  };
        return localVarApiClient.buildCall(basePath, localVarPath, "GET", localVarQueryParams, localVarCollectionQueryParams, localVarPostBody, localVarHeaderParams, localVarCookieParams, localVarFormParams, localVarAuthNames, _callback);
    }

    @SuppressWarnings("rawtypes")
    private okhttp3.Call getListOfCategoriesValidateBeforeCall(String xGIAuthorization, final ApiCallback _callback) throws ApiException {
        // verify the required parameter 'xGIAuthorization' is set
        if (xGIAuthorization == null) {
            throw new ApiException("Missing the required parameter 'xGIAuthorization' when calling getListOfCategories(Async)");
        }

        return getListOfCategoriesCall(xGIAuthorization, _callback);

    }

    /**
     * Get lists category
     * Returns all categories data master
     * @param xGIAuthorization Authorization (required)
     * @return CATEGORIESRESPONSE
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public CATEGORIESRESPONSE getListOfCategories(String xGIAuthorization) throws ApiException {
        ApiResponse<CATEGORIESRESPONSE> localVarResp = getListOfCategoriesWithHttpInfo(xGIAuthorization);
        return localVarResp.getData();
    }

    /**
     * Get lists category
     * Returns all categories data master
     * @param xGIAuthorization Authorization (required)
     * @return ApiResponse&lt;CATEGORIESRESPONSE&gt;
     * @throws ApiException If fail to call the API, e.g. server error or cannot deserialize the response body
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public ApiResponse<CATEGORIESRESPONSE> getListOfCategoriesWithHttpInfo(String xGIAuthorization) throws ApiException {
        okhttp3.Call localVarCall = getListOfCategoriesValidateBeforeCall(xGIAuthorization, null);
        Type localVarReturnType = new TypeToken<CATEGORIESRESPONSE>(){}.getType();
        return localVarApiClient.execute(localVarCall, localVarReturnType);
    }

    /**
     * Get lists category (asynchronously)
     * Returns all categories data master
     * @param xGIAuthorization Authorization (required)
     * @param _callback The callback to be executed when the API call finishes
     * @return The request call
     * @throws ApiException If fail to process the API call, e.g. serializing the request body object
     * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
        <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
        <tr><td> 200 </td><td> Success </td><td>  -  </td></tr>
        <tr><td> 400 </td><td> Bad Request </td><td>  -  </td></tr>
        <tr><td> 401 </td><td> Unauthenticated </td><td>  -  </td></tr>
        <tr><td> 404 </td><td> Request not found </td><td>  -  </td></tr>
        <tr><td> 500 </td><td> System error </td><td>  -  </td></tr>
     </table>
     */
    public okhttp3.Call getListOfCategoriesAsync(String xGIAuthorization, final ApiCallback<CATEGORIESRESPONSE> _callback) throws ApiException {

        okhttp3.Call localVarCall = getListOfCategoriesValidateBeforeCall(xGIAuthorization, _callback);
        Type localVarReturnType = new TypeToken<CATEGORIESRESPONSE>(){}.getType();
        localVarApiClient.executeAsync(localVarCall, localVarReturnType, _callback);
        return localVarCall;
    }
}
